Metrics wide fixes and refactors (#46)
- Introduce one ErrMetricMissing error instead of having one for
  each client and then try to errors.Join them (did not work as expected)
- Change log.V(5).Error to log.V(5).Info as log levels are not respected
  in Errors and are dumped as default level

Signed-off-by: Rafal Lal <rafal.lal@amd.com>